name: rankmyroast
description: "A menu creation tool with a collaborative ranking system"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: any
  file_picker: any
  go_router: any
  go_router_builder: any
  google_sign_in: any
  gap: any
  flutter_screenutil: any
  permission_handler: any
  image_picker: any
  uuid: any
  cached_network_image: ^3.4.1
  image_cropper: ^12.2.0
  cupertino_icons: any
  sqflite: any
  syncfusion_flutter_calendar: ^31.1.19
  timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/rankmyroast_icon.png
    - assets/images/rankmyroast_icon2.png
    - assets/images/rankmyroast_icon3.png
    - assets/images/rankmyroast_icon4.png
    - packages/timezone/data/latest_all.tzf
  
  fonts:
    - family: opensans
      fonts: 
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
    
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf



